#!/bin/bash

# Variables attendues dans le fichier de configuration
# groupsat: fichier de gestion des dates de fin - défaut: /etc/${CMD}.txt
# cluster: Nom du cluster (sujet du mail) - défaut: cluster
# log: nom du fichier de log - défaut: /var/log/${CMD}.log
# grplocal: nom du groupe local contennant les administrateurs temporaires - défaut: ${CMD}
# from: adresse mail origine des mails - défaut: root@$(hostname)
# to: adresse mail destinataire des mails - défaut: root@$(hostname)


CMD="$(basename $0)"
groupsat="/etc/${CMD}.txt"
cluster="cluster"
log="/var/log/${CMD}.log"
grplocal="${CMD}"
from="root@$(hostname)"
to="root@$(hostname)"

if [ -r /etc/${CMD}.conf ]
then
        . /etc/${CMD}.conf
else
        echo "Configuration file not found: /etc/${CMD}.conf"
        exit 1
fi

daydate=`date +"%Y-%m-%d"`
red="\033[0;31m"
fcd="\033[0m"
ok="[\033[0;32mok\033[0m]"
bodymail="$(mktemp /tmp/admtemp.XXXXXXXXXX)"

error () {
  echo ""
  echo -e "$red /!\ Error: $1 $fcd \n"
  print_help
  exit 1
}

print_help () {

    echo "
USAGE 1: $CMD add NNI -d date_end
Add user **** to local sudoers group ${grplocal}  ( date format YYYYMMDD )

USAGE 2: $CMD del NNI
Remove user **** to local sudoers group ${grplocal}

USAGE 3: $CMD mod NNI -d date_end
Change date of user **** in local sudoers group ${grplocal}

USAGE 5: $CMD check 
Check status group ${grplocal}

USAGE 4: $CMD status 
Display status group ${grplocal}

"

  exit 1
}

getent group ${grplocal} 1>/dev/null

if [ $? -eq 1 ]
then
  echo "" > $bodymail
  echo "Bonjour," >> $bodymail
  echo "" >> $bodymail
  echo "Le group ${grplocal} n'existe pas sur cette machine." >> $bodymail
  echo "" >> $bodymail
  status_at >> $bodymail
  echo -e "Content-Type:text/plain;charset=\"utf-8\"\nSubject: $sujetmail\nFrom:$from\nTo:$to\n`cat $bodymail`\n" |/usr/sbin/sendmail -f "$from" "$to"
  error "Le group ${grplocal} n'existe pas sur cette machine."
fi

add_nni () {

        if [ "$#" -le "2" -o "$2" != "-d" ] ; then
                error "Syntax error"
        fi

        login=$1
        date_end=$3

        # Verification de l'existence de l'utilisateur dans le ldap
        if [ -z "$(getent passwd $login)" ];then
                error "Opération impossible le login $login n'existe pas"
        fi

        # Verification de la date 
        var=$(date -d $date_end 2>&1 1>/dev/null)
        date_jour=$(date +"%Y%m%d")

        if [ $? != 0 ];then
                error "La date n'est pas au bon format ou elle n'existe pas"
        fi
        if [ $date_end -lt $date_jour ];then
                error "La date insérée est antérieure à la date du jour "
        fi

        # Verification de la présence ou non de l'utilisateur dans le groupe
        if [ -n "$( getent group $grplocal | grep $login )" ];then
                error "Opération impossible l'utilisateur possédent déjà  le groupe $grplocal "
        else
                /usr/sbin/addgroup $login $grplocal
                echo -e "[ $daydate ] - Ajout du groupe $grplocal au compte $login jusq'au $date_end" >> $log
                echo -e "$date_jour:$login:$date_end" >> $groupsat
        fi
}

del_nni () {


        # Verification de la syntaxe
        if [ "$#" -lt "1" ] ; then
                error "Syntax error"
        fi
        login=$1

        # Verification de l'existence de l'utilisateur dans le ldap
        if [ -z "$(getent passwd $login)" ];then
                error "Opération impossible le login $login n'existe pas"
        fi

        # Verification de la présence ou non de l'utilisateur dans le groupe
        if [ -z "$( getent group $grplocal | grep $login )" ];then
                error "Opération impossible l'utilisateur ne posséde pas le groupe $grplocal "
        else
                /usr/sbin/delgroup $login $grplocal
                pkill -9 -u $login
                echo -e "[ $daydate ] - Supression du compte $login du groupe $grplocal " >> $log
                sed -i "/"$login"/d" $groupsat
        fi

}

mod_nni () {

        if [ "$#" -le "2" -o "$2" != "-d" ] ; then
                error "Syntax error"
        fi

        login=$1
        date_end=$3

        # Verification de l'existence de l'utilisateur dans le ldap
        if [ -z "$(getent passwd $login)" ];then
                error "Opération impossible le login $login n'existe pas"
        fi

        # Verification de la date 
        var=$(date -d $date_end 2>&1 1>/dev/null)
        date_jour=$(date +"%Y%m%d")

        if [ $? != 0 ];then
                error "La date n'est pas au bon format ou elle n'existe pas"
        fi
        if [ $date_end -lt $date_jour ];then
                error "La date insérée est antérieure à la date du jour "
        fi

        # Verification de la présence ou non de l'utilisateur dans le groupe
        if [ -n "$( getent group $grplocal | grep $login )" ];then
                echo -e "[ $daydate ] - Modification de la date de fin de validité du compte $login" >>$log
                sed -i "/"$login"/d" $groupsat
                echo -e "$date_jour:$login:$date_end" >> $groupsat
        else
                error "Opération impossible: l'utilisateur ne posséde pas le groupe $grpcal"
        fi

}

check_at () {

        if [ ! -f $groupsat ];then
                sujetmail="[ $cluster ] /!\ Error du script ${CMD}"
                echo "" > $bodymail
                echo "Bonjour," >> $bodymail
                echo "" >> $bodymail
                echo "Impossible de controler les admins temporaires , le fichier $groupsat n'est pas present"
                echo "" >> $bodymail
                echo -e "Content-Type:text/plain;charset=\"utf-8\"\nSubject: $sujetmail\nFrom:$from\nTo:$to\n`cat $bodymail`\n" |/usr/sbin/sendmail -f "$from" "$to"
        fi
        date_jour=$(date +%Y%m%d)
        check_perim=$(cat $groupsat)
        for i in $check_perim;do
                date_perimuser=$(echo $i | awk -F  ":" '{print$3}')
                login=$(echo $i | awk -F  ":" '{print$2}')
                if [ $date_perimuser -lt $date_jour ];then
                        sujetmail="[ $cluster ] Suppression du compte $login du group ${grplocal}"
                        echo "" > $bodymail
                        echo "Bonjour," >> $bodymail
                        echo "" >> $bodymail
                        echo "Le compte $login etant arrive a expiration, il a ete supprime du group $grplocal" >> $bodymail
                        echo "Les connexions actives ont ete killees" >> $bodymail
                        echo "" >> $bodymail
                        status_at >> $bodymail
                        del_nni $login && echo -e "Content-Type:text/plain;charset=\"utf-8\"\nSubject: $sujetmail\nFrom:$from\nTo:$to\n`cat $bodymail`\n" |/usr/sbin/sendmail -f "$from" "$to"
                fi
        done
        listadmin=$(getent group $grplocal | awk -F ":" '{print$4}' | tr "," " ")
        for a in $listadmin;do
                grep $a $groupsat 1>/dev/null
                if [ $? != "0" ];then
                        sujetmail='[ '$cluster' ] Suppression du compte '$a' du group '${grplocal}' ( /!\ user absent du fichier '$groupsat' )'
                        echo "" > $bodymail
                        echo "Bonjour," >> $bodymail
                        echo "" >> $bodymail
                        echo "Le compte $a n etant pas present dans le fichier $groupsat, il a ete supprime du group $grplocal" >> $bodymail
                        echo "Les connexions actives ont ete killees" >> $bodymail
                        echo "" >> $bodymail
                        status_at >> $bodymail
                        del_nni $a && echo -e "Content-Type:text/plain;charset=\"utf-8\"\nSubject: $sujetmail\nFrom:$from\nTo:$to\n`cat $bodymail`\n" |/usr/sbin/sendmail -f "$from" "$to"
                fi
        done
        listuseradmin=$(awk -F ":" '{print$2}' ${groupsat})
        for x in $listuseradmin;do
                grep $x /etc/group 1>/dev/null
                if [ $? != 0 ];then
                        /etc/init.d/sssd restart
                        /usr/sbin/addgroup $x $grplocal
                        sujetmail="[ $cluster ] /!\ User $x absent du group $grplocal"
                        echo "" > $bodymail
                        echo "Bonjour," >> $bodymail
                        echo "" >> $bodymail
                        echo "Le compte $x à été rajouté au group $grplocal car il était absent du group $grplocal"
                        echo "" >> $bodymail
                        status_at >> $bodymail
                        echo -e "Content-Type:text/plain;charset=\"utf-8\"\nSubject: $sujetmail\nFrom:$from\nTo:$to\n`cat $bodymail`\n" |/usr/sbin/sendmail -f "$from" "$to"
                fi
        done

        echo ""
        echo -e "$ok Check status date d expiration des comptes dans le group $grplocal $fcd"
        status_at
}

status_at () {

        lign15='---------------'
        echo ""
        printf "%15s %15s %15s\n" Date_de_debut NNI Date_de_Fin
        printf "%15s %15s %15s\n" $lign15 $lign15 $lign15
        listusers=$(cat $groupsat)
        for i in $listusers;do
                begin_day=$(date -d $(echo $i | awk -F ":" '{print$1}' ) "+%Y-%m-%d")
                end_day=$(date -d $(echo $i | awk -F ":" '{print$3}' ) "+%Y-%m-%d")
                nni=$(echo $i | awk -F ":" '{print$2}' )
                printf "%15s %15s %15s\n" $begin_day $nni $end_day
        done
        echo ""
}

ACTION=${1}
shift

case ${ACTION} in
  add)
    add_nni $*
    ;;
  del)
    del_nni $*
    ;;
  mod)
    mod_nni $*
    ;;
  check)
    check_at $*
    ;;
  status)
    status_at $*
    ;;
  *)
    print_help
    ;;
esac

[ -e ${bodymail} ] && rm -f ${bodymail}
