#!/bin/bash
#####################################################################
# Script to backup SlurmDBD database 
#####################################################################
# NOTE: This file is automatically generated by puppet.
# Changes to this file will be overwritten periodically by puppet!
#####################################################################

source ./slurmdbd-backup.var 


print_error () {
        case ${1} in
        1)
                echo -e "${2}: \e[00;31m File not found, cannot proceed. \e[00m" 
        ;;
	2)
		echo -e "\e[00;31m An error occurred while executing mysqldump. \e[00m"
	;;
        esac
        exit ${1}
}


if [ -d ${BKDIR} ]
then
  TODAY=$(date +%d_%m_%Y)
  NOW=$(date +%Hh%M)
  [ -d ${BKDIR}/${TODAY} ] || mkdir ${BKDIR}/${TODAY}
  ln -Tfs ${BKDIR}/${TODAY} ${BKDIR}/last
    mysqldump --defaults-extra-file=${DBMAINCONF} -F -l --databases ${SLURMDB} ${ACCTDB} > ${BKDIR}/${TODAY}/slurmdbds_$(hostname)_${TODAY}_${NOW}.sql || print_error 2
else
  print_error 1 ${BKDIR}
fi
 
