#!/bin/sh
##########################################################################
#  Puppet configuration file                                             #
#                                                                        #
#  Copyright (C) 2014-2017 EDF S.A.                                      #
#  Contact: CCN-HPC <dsp-cspit-ccn-hpc@edf.fr>                           #
#                                                                        #
#  This program is free software; you can redistribute in and/or         #
#  modify it under the terms of the GNU General Public License,          #
#  version 2, as published by the Free Software Foundation.              #
#  This program is distributed in the hope that it will be useful,       #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU General Public License for more details.                          #
##########################################################################

# This script is designed to setup Infiniband and Omni-Path devices mode with
# optional ib-mode parameter.

[ -z "$IF_IB_MODE" ] && exit 0

echo "pre-up: setting IB mode $IF_IB_MODE on $IFACE"
echo $IF_IB_MODE > /sys/class/net/$IFACE/mode || true

exit 0
