#!/bin/sh
##########################################################################
#  Puppet configuration file                                             #
#                                                                        #
#  Copyright (C) 2014-2017 EDF S.A.                                      #
#  Contact: CCN-HPC <dsp-cspit-ccn-hpc@edf.fr>                           #
#                                                                        #
#  This program is free software; you can redistribute in and/or         #
#  modify it under the terms of the GNU General Public License,          #
#  version 2, as published by the Free Software Foundation.              #
#  This program is distributed in the hope that it will be useful,       #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU General Public License for more details.                          #
##########################################################################

# This script is designed to kill eventual instances of dhclient running on
# network interfaces. This is typically usefull in diskless environment where
# default /etc/network/interfaces files in live image is setup with dynamic
# (DHCP) interfaces, initialized as this very early in the boot process (with
# dhclient process) and then setup as static interface (with networking service
# restart) by Puppet later. To make sure interfaces such as bond slaves,
# configured in manual mode in Puppet version of /etc/network/interfaces, do not
# have any dhclient process attached that would kill bonding setup after DHCP
# request renewal, kill the process here.

[ "$VERBOSITY" = 1 ] && set -x

# exit here on initial call with IFACE --all
[ "$ADDRFAM" = meta ] && exit 0

# kill eventual dhclient running for IFACE
echo "pre-up: killing dhclient for $IFACE"
pkill -e -f "^dhclient.*$IFACE" || true

exit 0
